### ISSUE TITLE
More data is needed from a midi file in Tegridy-Piano-CC-BY-NC-SA dataset

### ISSUE THREAD

**Issue by Menorah** [asigalov61/Tegridy-MIDI-Dataset#2]
Hi, I was wondering if there is any extra information (composer name, album, etc) available from the "Break Through.mid" file.

Thank you.

**Comment by asigalov61** [comment]
@Menorah Hello and thank you for your question...

All compositions in Tegridy Piano were composed by me (Aleksandr Sigalov) and OpenAI's MuseNet Music AI system.

The "Break Through" composition is a MuseNet continuation of a pop Russian song with the same name. So the first 30 seconds are the original and the rest is my work.

Hope this answers your question.

Alex

**Comment by Menorah** [comment]
Hello, I can't find the Russian pop song anywhere, would you be so kind as to provide me with a reference link?
Thank you

**Comment by asigalov61** [comment]
Yes, sure...

Here is the original: https://www.youtube.com/watch?v=LxkFBX1m8FU

**Comment by Menorah** [comment]
Thanks !!!
